import {
  app,
  HttpRequest,
  HttpResponseInit,
  InvocationContext,
} from '@azure/functions';
import ExcelJS from 'exceljs';
import { validateUser, unauthorizedResponse, errorResponse, jsonResponse } from '../lib/auth/validateUser';
import { uploadExcelReport, generateSasUrl } from '../lib/storage/blobClient';
import { upsertReport, getReports } from '../lib/storage/tableClient';
import {
  getCostData,
  getSavingsLog,
  getIdleResources,
  getRightsizing,
  getAHBRecommendations,
  getStorageRecommendations,
  getDatabaseRecommendations,
  getBudgets,
} from '../lib/storage/tableClient';

const DARK_BLUE = '1E3A5F';
const LIGHT_GRAY = 'F5F5F5';
const RED = 'FF4444';
const AMBER = 'FFAA00';
const GREEN = '22C55E';

function formatUSD(value: number): string {
  return `$${value.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ',')}`;
}

function applyHeaderStyle(row: ExcelJS.Row, bg = DARK_BLUE): void {
  row.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 11 };
    cell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: `FF${bg}` },
    };
    cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true };
    cell.border = {
      top: { style: 'thin' },
      left: { style: 'thin' },
      bottom: { style: 'thin' },
      right: { style: 'thin' },
    };
  });
}

function applyDataRow(row: ExcelJS.Row, isAlt: boolean): void {
  const bg = isAlt ? LIGHT_GRAY : 'FFFFFF';
  row.eachCell((cell) => {
    cell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: `FF${bg}` },
    };
    cell.border = {
      top: { style: 'thin', color: { argb: 'FFE0E0E0' } },
      left: { style: 'thin', color: { argb: 'FFE0E0E0' } },
      bottom: { style: 'thin', color: { argb: 'FFE0E0E0' } },
      right: { style: 'thin', color: { argb: 'FFE0E0E0' } },
    };
    cell.alignment = { vertical: 'middle' };
  });
}

function generateId(): string {
  return Date.now().toString(36) + Math.random().toString(36).slice(2);
}

async function generateExcelHttp(
  request: HttpRequest,
  context: InvocationContext
): Promise<HttpResponseInit> {
  let user;
  try {
    user = await validateUser(request);
  } catch {
    return unauthorizedResponse();
  }

  let reportMonth = new Date().toISOString().slice(0, 7);
  let reportId = '';

  try {
    const body = (await request.json()) as { month?: string } | null;
    reportMonth = (body as { month?: string } | null)?.month ?? reportMonth;

    reportId = generateId();
    const fileName = `report-${reportMonth}-${reportId}.xlsx`;

    // Create initial report record
    await upsertReport({
      partitionKey: 'reports',
      rowKey: reportId,
      reportMonth,
      generatedAt: new Date().toISOString(),
      generatedBy: user.email,
      blobUrl: '',
      sasUrl: '',
      status: 'generating',
      errorMessage: '',
    });

    // Fetch all data
    const [costData, savings, idleResources, rightsizing, ahb, storage, databases, budgets] =
      await Promise.all([
        getCostData('all'),
        getSavingsLog(),
        getIdleResources(),
        getRightsizing(),
        getAHBRecommendations(),
        getStorageRecommendations(),
        getDatabaseRecommendations(),
        getBudgets(),
      ]);

    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'AzureOptimize Pro';
    workbook.created = new Date();

    // ─── Tab 1: Executive Summary ────────────────────────────────────────
    const summarySheet = workbook.addWorksheet('Executive Summary');
    summarySheet.columns = [
      { width: 30 }, { width: 20 }, { width: 20 }, { width: 20 },
    ];

    // Title
    const titleRow = summarySheet.addRow(['AzureOptimize Pro — Monthly Cost Report']);
    titleRow.getCell(1).font = { bold: true, size: 16, color: { argb: `FF${DARK_BLUE}` } };
    summarySheet.addRow([`Report Period: ${reportMonth}`]);
    summarySheet.addRow([`Generated: ${new Date().toLocaleDateString()}`]);
    summarySheet.addRow([`Generated By: ${user.email}`]);
    summarySheet.addRow([]);

    const totalMTD = costData.reduce((s, d) => s + d.totalCost, 0);
    const totalPrev = costData.reduce((s, d) => s + d.previousMonthCost, 0);
    const totalForecasted = costData.reduce((s, d) => s + d.forecastedCost, 0);
    const momChange = totalMTD - totalPrev;
    const momPercent = totalPrev > 0 ? (momChange / totalPrev) * 100 : 0;

    const monthSavings = savings
      .filter((s) => s.implementedAt.startsWith(reportMonth))
      .reduce((sum, s) => sum + s.projectedMonthlySaving, 0);

    const potentialSavings =
      idleResources.reduce((s, r) => s + r.estimatedMonthlyCost, 0) +
      rightsizing.reduce((s, r) => s + r.monthlySaving, 0) +
      ahb.reduce((s, r) => s + r.savingWithAHB, 0) +
      storage.reduce((s, r) => s + r.estimatedMonthlySaving, 0) +
      databases.reduce((s, r) => s + r.estimatedMonthlySaving, 0);

    const metricsHeader = summarySheet.addRow(['Metric', 'Value', 'Previous Month', 'Change']);
    applyHeaderStyle(metricsHeader);

    const metricsRows = [
      ['Total Azure Spend (MTD)', formatUSD(totalMTD), formatUSD(totalPrev), `${momChange >= 0 ? '+' : ''}${formatUSD(momChange)} (${momPercent.toFixed(1)}%)`],
      ['Forecasted Month-End Spend', formatUSD(totalForecasted), '', ''],
      ['Savings Implemented This Month', formatUSD(monthSavings), '', ''],
      ['Potential Savings Remaining', formatUSD(potentialSavings), '', ''],
      ['Total Subscriptions', String(costData.length), '', ''],
    ];

    metricsRows.forEach((row, i) => {
      const r = summarySheet.addRow(row);
      applyDataRow(r, i % 2 === 0);
      r.getCell(2).font = { bold: true };
    });

    summarySheet.views = [{ state: 'frozen', ySplit: 6 }];

    // ─── Tab 2: Savings Implemented ──────────────────────────────────────
    const savingsSheet = workbook.addWorksheet('Savings Implemented');
    savingsSheet.columns = [
      { header: 'Date', key: 'date', width: 14 },
      { header: 'Category', key: 'category', width: 20 },
      { header: 'Resource Name', key: 'resource', width: 30 },
      { header: 'Description', key: 'notes', width: 35 },
      { header: 'Monthly Saving ($)', key: 'monthly', width: 18 },
      { header: 'Annual Saving ($)', key: 'annual', width: 18 },
      { header: 'Implemented By', key: 'by', width: 25 },
    ];

    applyHeaderStyle(savingsSheet.getRow(1));
    savingsSheet.views = [{ state: 'frozen', ySplit: 1 }];

    let savingSubtotal = 0;
    const filteredSavings = savings.filter((s) =>
      s.implementedAt.startsWith(reportMonth)
    );

    filteredSavings.forEach((s, i) => {
      const r = savingsSheet.addRow({
        date: s.implementedAt.slice(0, 10),
        category: s.category,
        resource: s.resourceName,
        notes: s.notes || s.category,
        monthly: s.projectedMonthlySaving,
        annual: s.projectedMonthlySaving * 12,
        by: s.implementedBy,
      });
      applyDataRow(r, i % 2 === 0);
      r.getCell('monthly').numFmt = '$#,##0.00';
      r.getCell('annual').numFmt = '$#,##0.00';
      savingSubtotal += s.projectedMonthlySaving;
    });

    const savingSubtotalRow = savingsSheet.addRow({
      date: 'TOTAL',
      monthly: savingSubtotal,
      annual: savingSubtotal * 12,
    });
    applyHeaderStyle(savingSubtotalRow, '2D5A1B');
    savingSubtotalRow.getCell('monthly').numFmt = '$#,##0.00';
    savingSubtotalRow.getCell('annual').numFmt = '$#,##0.00';

    // ─── Tab 3: Open Recommendations ─────────────────────────────────────
    const recsSheet = workbook.addWorksheet('Open Recommendations');
    recsSheet.columns = [
      { header: 'Priority', key: 'priority', width: 12 },
      { header: 'Category', key: 'category', width: 20 },
      { header: 'Resource', key: 'resource', width: 30 },
      { header: 'Recommendation', key: 'rec', width: 40 },
      { header: 'Est. Monthly Saving ($)', key: 'monthly', width: 22 },
      { header: 'Est. Annual Saving ($)', key: 'annual', width: 22 },
      { header: 'Effort', key: 'effort', width: 12 },
    ];

    applyHeaderStyle(recsSheet.getRow(1));
    recsSheet.views = [{ state: 'frozen', ySplit: 1 }];

    const allRecs = [
      ...idleResources.map((r) => ({
        priority: r.estimatedMonthlyCost > 100 ? 'High' : 'Medium',
        category: 'Idle Resources',
        resource: r.resourceName,
        rec: `Delete ${r.resourceType}: ${r.resourceName}`,
        monthly: r.estimatedMonthlyCost,
        effort: 'Low',
      })),
      ...rightsizing.map((r) => ({
        priority: r.monthlySaving > 200 ? 'High' : 'Medium',
        category: 'VM Rightsizing',
        resource: r.vmName,
        rec: `Downsize from ${r.currentSku} to ${r.recommendedSku}`,
        monthly: r.monthlySaving,
        effort: 'Medium',
      })),
      ...ahb.map((r) => ({
        priority: 'High',
        category: 'Azure Hybrid Benefit',
        resource: r.resourceName,
        rec: `Enable AHB on ${r.resourceType}: ${r.resourceName}`,
        monthly: r.savingWithAHB,
        effort: 'Low',
      })),
      ...storage.map((r) => ({
        priority: r.estimatedMonthlySaving > 50 ? 'High' : 'Low',
        category: 'Storage Optimization',
        resource: r.resourceName,
        rec: r.recommendation,
        monthly: r.estimatedMonthlySaving,
        effort: 'Low',
      })),
      ...databases.map((r) => ({
        priority: r.estimatedMonthlySaving > 100 ? 'High' : 'Medium',
        category: 'Database Optimization',
        resource: r.resourceName,
        rec: r.recommendation,
        monthly: r.estimatedMonthlySaving,
        effort: 'Medium',
      })),
    ].sort((a, b) => b.monthly - a.monthly);

    let recsSubtotal = 0;
    allRecs.forEach((rec, i) => {
      const r = recsSheet.addRow({ ...rec, annual: rec.monthly * 12 });
      applyDataRow(r, i % 2 === 0);

      // Color priority cell
      const priorityCell = r.getCell('priority');
      if (rec.priority === 'High') {
        priorityCell.fill = {
          type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${RED}` },
        };
        priorityCell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
      } else if (rec.priority === 'Medium') {
        priorityCell.fill = {
          type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${AMBER}` },
        };
        priorityCell.font = { bold: true };
      } else {
        priorityCell.fill = {
          type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${GREEN}` },
        };
        priorityCell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
      }

      r.getCell('monthly').numFmt = '$#,##0.00';
      r.getCell('annual').numFmt = '$#,##0.00';
      recsSubtotal += rec.monthly;
    });

    const recsSubtotalRow = recsSheet.addRow({
      priority: 'TOTAL',
      monthly: recsSubtotal,
      annual: recsSubtotal * 12,
    });
    applyHeaderStyle(recsSubtotalRow, '5A1B2D');
    recsSubtotalRow.getCell('monthly').numFmt = '$#,##0.00';
    recsSubtotalRow.getCell('annual').numFmt = '$#,##0.00';

    // ─── Tab 4: Cost Breakdown ────────────────────────────────────────────
    const costSheet = workbook.addWorksheet('Cost Breakdown');
    costSheet.columns = [
      { header: 'Service / Resource', key: 'name', width: 35 },
      { header: 'This Month ($)', key: 'thisMonth', width: 16 },
      { header: 'Last Month ($)', key: 'lastMonth', width: 16 },
      { header: 'Delta ($)', key: 'delta', width: 14 },
    ];

    applyHeaderStyle(costSheet.getRow(1));
    costSheet.views = [{ state: 'frozen', ySplit: 1 }];

    const allServices: Record<string, number> = {};
    for (const cd of costData) {
      const services = JSON.parse(cd.serviceData || '[]') as Array<{ serviceName: string; cost: number }>;
      for (const s of services) {
        allServices[s.serviceName] = (allServices[s.serviceName] ?? 0) + s.cost;
      }
    }

    Object.entries(allServices)
      .sort(([, a], [, b]) => b - a)
      .slice(0, 20)
      .forEach(([name, cost], i) => {
        const r = costSheet.addRow({ name, thisMonth: cost, lastMonth: 0, delta: cost });
        applyDataRow(r, i % 2 === 0);
        r.getCell('thisMonth').numFmt = '$#,##0.00';
        r.getCell('lastMonth').numFmt = '$#,##0.00';
        r.getCell('delta').numFmt = '$#,##0.00';
      });

    // ─── Tab 5: Budget Status ─────────────────────────────────────────────
    const budgetSheet = workbook.addWorksheet('Budget Status');
    budgetSheet.columns = [
      { header: 'Budget Name', key: 'name', width: 25 },
      { header: 'Scope', key: 'scope', width: 30 },
      { header: 'Monthly Limit ($)', key: 'limit', width: 16 },
      { header: 'Spent ($)', key: 'spent', width: 14 },
      { header: '% Used', key: 'pct', width: 10 },
      { header: 'Status', key: 'status', width: 12 },
    ];

    applyHeaderStyle(budgetSheet.getRow(1));
    budgetSheet.views = [{ state: 'frozen', ySplit: 1 }];

    budgets.forEach((b, i) => {
      const pct = b.amount > 0 ? Math.round((b.currentSpend / b.amount) * 100) : 0;
      const status = pct >= 100 ? 'Over' : pct >= 80 ? 'At Risk' : 'On Track';
      const r = budgetSheet.addRow({
        name: b.name,
        scope: b.scope,
        limit: b.amount,
        spent: b.currentSpend,
        pct: `${pct}%`,
        status,
      });
      applyDataRow(r, i % 2 === 0);
      r.getCell('limit').numFmt = '$#,##0.00';
      r.getCell('spent').numFmt = '$#,##0.00';

      const statusCell = r.getCell('status');
      if (status === 'Over') {
        statusCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${RED}` } };
        statusCell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
      } else if (status === 'At Risk') {
        statusCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${AMBER}` } };
        statusCell.font = { bold: true };
      } else {
        statusCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${GREEN}` } };
        statusCell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
      }
    });

    // Generate and upload
    const buffer = Buffer.from(await workbook.xlsx.writeBuffer());
    const blobUrl = await uploadExcelReport(fileName, buffer);
    const sasUrl = await generateSasUrl(blobUrl);

    await upsertReport({
      partitionKey: 'reports',
      rowKey: reportId,
      reportMonth,
      generatedAt: new Date().toISOString(),
      generatedBy: user.email,
      blobUrl,
      sasUrl,
      status: 'ready',
      errorMessage: '',
    });

    context.log(`Report generated by ${user.email}: ${fileName}`);
    return jsonResponse({ reportId, fileName, downloadUrl: sasUrl, reportMonth });
  } catch (err) {
    context.error('Error generating Excel report:', err);
    // Mark report as failed so it doesn't stay stuck in 'generating' state
    if (reportId) {
      upsertReport({
        partitionKey: 'reports',
        rowKey: reportId,
        reportMonth,
        generatedAt: new Date().toISOString(),
        generatedBy: user?.email ?? '',
        blobUrl: '',
        sasUrl: '',
        status: 'error',
        errorMessage: err instanceof Error ? err.message : String(err),
      }).catch((e: unknown) => context.error('Failed to update report status to failed:', e));
    }
    return errorResponse('Failed to generate report');
  }
}

async function getReportsHttp(
  request: HttpRequest,
  context: InvocationContext
): Promise<HttpResponseInit> {
  try {
    await validateUser(request);
  } catch {
    return unauthorizedResponse();
  }

  try {
    const reports = await getReports();
    return jsonResponse({
      data: reports.map((r) => ({
        id: r.rowKey,
        reportMonth: r.reportMonth,
        generatedAt: r.generatedAt,
        generatedBy: r.generatedBy,
        downloadUrl: r.sasUrl || r.blobUrl,
        status: r.status,
      })),
    });
  } catch (err) {
    context.error('Error fetching reports:', err);
    return errorResponse('Failed to fetch reports');
  }
}

app.http('generateExcel', {
  methods: ['POST'],
  authLevel: 'anonymous',
  route: 'reports/generate',
  handler: generateExcelHttp,
});

app.http('getReports', {
  methods: ['GET'],
  authLevel: 'anonymous',
  route: 'reports',
  handler: getReportsHttp,
});
